version: '3.8'

services:
  app:
    image: radiocat2000/stock:v1
    container_name: stock-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-twilight-darkness-a10m1qtu-pooler.ap-southeast-1.aws.neon.tech/stock?user=neondb_owner&password=npg_7EGx3vYfAaVh&sslmode=require&channelBinding=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kanishka23
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      BPL_JVM_CALCULATE_HEAP: false
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
    extra_hosts:
      - "host.docker.internal:host-gateway"   # needed on Linux to resolve host.docker.internal


#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysqldb
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=kanishka23
#      - MYSQL_DATABASE=Stock
#    volumes:
#      - mysql:/var/lib/mysql
#
#volumes:
#  mysql:
