spring.application.name=StockMGT

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/stock
spring.datasource.url=jdbc:postgresql://ep-twilight-darkness-a10m1qtu-pooler.ap-southeast-1.aws.neon.tech/stock?user=neondb_owner&password=npg_7EGx3vYfAaVh&sslmode=require&channelBinding=require
spring.datasource.username=postgres
spring.datasource.password=kanishka23

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.security.user.name=user
spring.security.user.password=password

# Hibernate & JPA Performance Optimization
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# HikariCP Performance Settings for Low Spec Server
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

app.bootstrap-admin.username=admin
app.bootstrap-admin.password=radiocat@123